import { Candidate } from "@/types/candidate";

export const NATIONAL_CANDIDATES: Record<string, Candidate> = {
  melenchon: {
    id: "melenchon",
    name: "Jean-Luc Mélenchon",
    party: "LFI",
    role: "Député, fondateur LFI",
    color: "#C9462C",
    wikipedia: "Jean-Luc_Mélenchon",
    searchTerms: ["Jean-Luc Mélenchon", "Mélenchon"],
  },
  glucksmann: {
    id: "glucksmann",
    name: "Raphaël Glucksmann",
    party: "Place Publique/PS",
    role: "Député européen",
    color: "#FF69B4",
    wikipedia: "Raphaël_Glucksmann",
    searchTerms: ["Raphaël Glucksmann", "Glucksmann"],
  },
  ruffin: {
    id: "ruffin",
    name: "François Ruffin",
    party: "Picardie Debout",
    role: "Député",
    color: "#E85D75",
    wikipedia: "François_Ruffin",
    searchTerms: ["François Ruffin", "Ruffin"],
  },
  tondelier: {
    id: "tondelier",
    name: "Marine Tondelier",
    party: "EELV",
    role: "Secrétaire nationale EELV",
    color: "#00A86B",
    wikipedia: "Marine_Tondelier",
    searchTerms: ["Marine Tondelier", "Tondelier"],
  },
  faure: {
    id: "faure",
    name: "Olivier Faure",
    party: "PS",
    role: "Premier secrétaire PS",
    color: "#FF69B4",
    wikipedia: "Olivier_Faure_(homme_politique)",
    searchTerms: ["Olivier Faure"],
  },
  philippe: {
    id: "philippe",
    name: "Édouard Philippe",
    party: "Horizons",
    role: "Maire du Havre, ancien PM",
    color: "#4A90A4",
    wikipedia: "Édouard_Philippe",
    searchTerms: ["Édouard Philippe"],
  },
  attal: {
    id: "attal",
    name: "Gabriel Attal",
    party: "Renaissance",
    role: "Député, ancien PM",
    color: "#FFD700",
    wikipedia: "Gabriel_Attal",
    searchTerms: ["Gabriel Attal"],
    youtubeHandle: "@gabriel_attal",
  },
  darmanin: {
    id: "darmanin",
    name: "Gérald Darmanin",
    party: "Renaissance",
    role: "Ministre de l'Intérieur",
    color: "#FFD700",
    wikipedia: "Gérald_Darmanin",
    searchTerms: ["Gérald Darmanin", "Darmanin"],
  },
  retailleau: {
    id: "retailleau",
    name: "Bruno Retailleau",
    party: "LR",
    role: "Ministre de l'Intérieur",
    color: "#0066CC",
    wikipedia: "Bruno_Retailleau",
    searchTerms: ["Bruno Retailleau", "Retailleau"],
  },
  wauquiez: {
    id: "wauquiez",
    name: "Laurent Wauquiez",
    party: "LR",
    role: "Président Auvergne-Rhône-Alpes",
    color: "#0066CC",
    wikipedia: "Laurent_Wauquiez",
    searchTerms: ["Laurent Wauquiez", "Wauquiez"],
  },
  ciotti: {
    id: "ciotti",
    name: "Éric Ciotti",
    party: "UDR (ex-LR)",
    role: "Député",
    color: "#0D2C54",
    wikipedia: "Éric_Ciotti",
    searchTerms: ["Éric Ciotti", "Ciotti"],
  },
  bardella: {
    id: "bardella",
    name: "Jordan Bardella",
    party: "RN",
    role: "Président RN",
    color: "#0D2C54",
    wikipedia: "Jordan_Bardella",
    searchTerms: ["Jordan Bardella", "Bardella"],
    youtubeHandle: "@J_Bardella",
  },
  lepen: {
    id: "lepen",
    name: "Marine Le Pen",
    party: "RN",
    role: "Députée, ancienne présidente RN",
    color: "#0D2C54",
    wikipedia: "Marine_Le_Pen",
    searchTerms: ["Marine Le Pen"],
    youtubeHandle: "@MarineLePenOfficiel",
  },
  zemmour: {
    id: "zemmour",
    name: "Éric Zemmour",
    party: "Reconquête",
    role: "Président Reconquête",
    color: "#1E3A5F",
    wikipedia: "Éric_Zemmour",
    searchTerms: ["Éric Zemmour", "Zemmour"],
    youtubeHandle: "@EricZemmourOfficiel",
  },
  marechal: {
    id: "marechal",
    name: "Marion Maréchal",
    party: "Reconquête",
    role: "Vice-présidente Reconquête",
    color: "#1E3A5F",
    wikipedia: "Marion_Maréchal",
    searchTerms: ["Marion Maréchal"],
    youtubeHandle: "@MarionMarechalOfficiel",
  },
  knafo: {
    id: "knafo",
    name: "Sarah Knafo",
    party: "Reconquête",
    role: "Députée européenne",
    color: "#1E3A5F",
    wikipedia: "Sarah_Knafo",
    searchTerms: ["Sarah Knafo"],
    youtubeHandle: "@SarahKnafo-Videos",
    highlighted: true,
  },
  philippot: {
    id: "philippot",
    name: "Florian Philippot",
    party: "Les Patriotes",
    role: "Président Les Patriotes",
    color: "#00008B",
    wikipedia: "Florian_Philippot",
    searchTerms: ["Florian Philippot"],
    youtubeHandle: "@florianphilippot1",
  },
};

export const NATIONAL_CANDIDATE_IDS = Object.keys(NATIONAL_CANDIDATES);
export const NATIONAL_CANDIDATE_LIST = Object.values(NATIONAL_CANDIDATES);
